import Head from "next/head";

type Props = {
  title: String,
};

export default function Home({title = "React Avançado"}: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to{" "}
          <a href="https://nextjs.org">{title}!</a>
        </h1>
      </main>
    </div>
  );
}
